Repository gustavosantaella/finance, pull requests merged in 2023-06, with the labels that each got.

#41 Create restore finance
  app/Http/Controllers/Api/WalletHistoryController.php
  app/Repositories/WalletHistoryRepository.php
  app/Services/WalletHistoryService.php
  routes/api.php
Labels: feature, finished, pending to approve

#45 fix: structure
  app/Http/Controllers/Api/Auth/AuthController.php
  app/Http/Controllers/Api/CategoryController.php
  app/Http/Controllers/Api/CountryController.php
  app/Http/Controllers/Api/UserController.php
  app/Http/Controllers/Api/WalletController.php
  app/Http/Controllers/Api/WalletHistoryController.php
  app/Services/Auth/AuthService.php
  app/Services/Category/CategoryService.php
  app/Services/Country/CountryService.php
  app/Services/Email/EmailService.php
  app/Services/Service.php
  app/Services/User/UserService.php
  app/Services/Wallet/WalletHistoryService.php
  app/Services/Wallet/WalletOperationService.php
  app/Services/Wallet/WalletService.php
  app/Services/schedules/FinanceScheduleService.php
  routes/api.php
Labels: hotfix, finished, pending to approve

#48 issue-47
  app/Helpers/traits/ResponseTrait.php
  app/Http/Controllers/Api/ApiController.php
  app/Http/Controllers/Api/LoanController.php
  app/Http/Requests/LoanRequest.php
  app/Models/Loan.php
  app/Repositories/CategoryRepository.php
  app/Repositories/LoanRepository.php
  app/Repositories/Repository.php
  app/Services/Category/CategoryService.php
  app/Services/Loan/LoanService.php
  app/Services/Wallet/WalletService.php
  config/definitions.php
  routes/api.php
Labels: feature, pending to approve, pending to deploy

#54 dev
  app/Repositories/Repository.php
  app/Services/Loan/LoanService.php
Labels: bug

#61 hotfixs
  .github/workflows/prod.yml
  app/Services/User/UserService.php
  start.sh
Labels: bug, pending to approve, pending to deploy, fixed

#62 hotfixs (#61)
  .github/workflows/prod.yml
  app/Services/User/UserService.php
  start.sh
Labels: bug, feature, pending to deploy, fixed
